version: "3.8"

services:
    fastapi-app:
        build: .
        container_name: rag_chatbot_api
        ports:
            - "8100:8100"
        volumes:
            - ./cache:/app/cache
            - ./data:/app/data
            - ./db:/app/db
        depends_on:
            - ollama
        environment:
            - OLLAMA_HOST=ollama
            - OLLAMA_BASE_URL=http://ollama:11434
        networks:
            - rag_network

    ollama:
        image: docker.io/ollama/ollama
        container_name: ollama_service
        ports:
            - "11434:11434"
        volumes:
            - ollama_data:/root/.ollama
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
        networks:
            - rag_network

volumes:
    ollama_data:

networks:
    rag_network:
        driver: bridge
