[tools]
node = "24.7.0"
pnpm = "10.15.1"
python = "3.11.13"
uv = "0.8.15"

[tasks.setup]
run = [
	"uv venv --clear",
	". .venv/bin/activate",
	"uv pip install -r requirements.txt",
	"pnpm install --dir web_app"
]

[tasks.dev]
run = [
  "docker compose up -d ollama",
  "uvicorn fastapi_app.main:app --reload --port 8100 &",
  "cd web_app && pnpm dev"
]

[tasks.deploy]
run = [
  "docker compose up --build -d",
  "cd web_app && pnpm build && pm2 start pm2.config.cjs --update-env"
]
