name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Set up mise
        uses: jdx/mise-action@main

      - name: Deploy package via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          source: "fastapi_app/*,web_app/*,.python-version,docker-compose.yml,Dockerfile,mise.toml,pyproject.toml,requirements.txt,uv.lock"
          target: ${{ secrets.DEPLOY_TARGET }}
          rm: false
          overwrite: true

      - name: Unpack and Deploy on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            cd ${{ secrets.DEPLOY_TARGET }}
            ~/.local/bin/mise install
            ~/.local/bin/mise run setup
            ~/.local/bin/mise run deploy
